{% set name = "thucyd" %}
{% set version = "0.2.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "7cd3c628bef6b6c59d8204524c4a5a3e443fc91591fd061463c04053a0d2ca45"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy >=1.23
    - python >=3.7

test:
  imports:
    - thucyd
  commands:
    - pip check
  requires:
    - pip

about:
  home: "https://gitlab.com/thucyd-dev/thucyd"
  license: Apache-2.0
  license_family: "APACHE"
  license_file: LICENSE
  summary: Reference library for advanced eigenanalysis.
  dev_url: https://gitlab.com/thucyd-dev/thucyd

extra:
  recipe-maintainers:
    - jaydamask
