travis:
  secure:
    BINSTAR_TOKEN: lsbnv304gzyM6GIsGhKGAcTGmpZFq1lbQiQE4gjYwEklJMlwSGkQRxRhHEDoGrd1jrfy7cVy3erW/iNY18m9bAfbUR1XPuLVSZrfQs4D1FmgzgYUW2WiMybxJtafgcU6Wp8LVh6usKLDdpO/NF48ZN4+zHX9boH1wvZPrJXKg5oKACntYEe3JglSmggvE5LeggXnVv8KLNbYoYCV71fd7wVh9K2dT21ciCUwODeoTcZy6XCTeNdzjXeohcRlF3XiETNh2FP7bDghLI2gTcvFXcY8F9qRP7gmOkmLjhD3b7G2Dt3k1/yG6r/aXeVfi40FofTQEp9dSBbE8EGsNdXQkcqjXj9D26wLmiQgX+E1pbPXRjP1zPa7l2sQQYUCklSqQy0Ozs8nqzgRG+le04dXtQoGsogbPZcTy4sItnZlzj45ldUZhEPCwNLJRC7/AHrNu5ufxA8U24UoBEd3l+lnXn/ANYlWbrHOrxIo5icsWV0ReMjgRPC/dMwofu2GJfZW5XScUS0opzMzu6LrFuYSBKXk0S4cJ9yJ1KK7o10O0C6IMaOGHJpCeMB/G8UJLJEZ9fpEl8Vo7v4zEUaKY47Ln33iB/XfwXe2V1UQeyUSS1+55slSNx8SYJ+nEtGP871whNwBInWVDs0XYwWa9O6FtP8P45qJS4NeXzn39pqMZag=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
